import { FormEvent, useCallback, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Signal={type:string;detail:string}; type Evidence={kind:string;excerpt:string;occurredAt:string;recordLine:number};
type Thread={externalId:string;title:string|null;archived:boolean;lastActivity:string;resumeRef:string};
type Card={workstream:{id:string|null;name:string;origin:string};score:number;confidence:string;latestActivity:string;cwd:string|null;bestThread:Thread;relatedThreads:Thread[];relatedFiles:string[];signals:Signal[];latestEvidence:Evidence[]};
type State={query:string;best:Card|null}; type Status={databasePath:string;latestRun:null|{completedAt:string|null;status:string};counts:Record<string,number>};
type Recent={workstream:{id:string;name:string;origin:string};latestActivity:string;confidence:string;threadCount:number};
const examples=["resume widget repair","where did we implement sitemap.ts?","latest work on ShipReady safe apply"];
const labels:Record<string,string>={"manual-assignment":"Manual assignment","alias-match":"Alias match","workstream-name-match":"Title match","title-match":"Title match","evidence-text-match":"Evidence text match","file-reference-match":"File reference match","cwd-match":"Cwd match",recency:"Recency","high-term-coverage":"High term coverage","ignored-thread-exclusion":"Ignored matches excluded"};
const date=(v:string|null|undefined)=>v?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const route=()=>({detail:location.pathname.match(/^\/workstreams\/([^/]+)$/)?.[1],query:new URLSearchParams(location.search).get("q")??""});
async function getJson(url:string){const r=await fetch(url);const body=await r.json();if(!r.ok)throw new Error(body.error??"Request failed.");return body}
function App(){const initial=route();const [query,setQuery]=useState(initial.query);const [result,setResult]=useState<State|null>(null);const [detail,setDetail]=useState<{workstream:{status:string;aliases:string[]};card:Card}|null>(null);const [status,setStatus]=useState<Status|null>(null);const [recent,setRecent]=useState<Recent[]>([]);const [loading,setLoading]=useState(false);const [evidence,setEvidence]=useState(false);const [evidenceLoading,setEvidenceLoading]=useState(false);const [error,setError]=useState("");const [statusError,setStatusError]=useState("");const [refreshed,setRefreshed]=useState<string|null>(null);
const refreshStatus=useCallback(()=>getJson("/api/status").then(x=>{setStatus(x);setRefreshed(new Date().toISOString());setStatusError("")}).catch(()=>setStatusError("Index status could not be refreshed.")),[]);
const loadRoute=useCallback(async()=>{const r=route();setEvidence(false);setError("");setQuery(r.query);if(r.detail){setLoading(true);setResult(null);try{setDetail(await getJson(`/api/workstreams/${encodeURIComponent(r.detail)}`))}catch(e){setDetail(null);setError(e instanceof Error?e.message:"Workstream could not be loaded.")}finally{setLoading(false)}}else{setDetail(null);if(r.query){setLoading(true);try{setResult(await getJson(`/api/state?q=${encodeURIComponent(r.query)}`))}catch(e){setError(e instanceof Error?e.message:"Search failed.")}finally{setLoading(false)}}else setResult(null)}},[]);
useEffect(()=>{loadRoute();refreshStatus();getJson("/api/workstreams/recent").then(x=>setRecent(x.workstreams)).catch(()=>{});const pop=()=>loadRoute();addEventListener("popstate",pop);const timer=setInterval(refreshStatus,30000);return()=>{removeEventListener("popstate",pop);clearInterval(timer)}},[loadRoute,refreshStatus]);
function search(e?:FormEvent){e?.preventDefault();const q=query.trim();if(!q)return;history.pushState({},"",`/search?q=${encodeURIComponent(q)}`);loadRoute()}
async function toggleEvidence(){if(evidence){setEvidence(false);return}const card=detail?.card??result?.best;if(!card)return;setEvidenceLoading(true);try{const body=detail?await getJson(`/api/workstreams/${encodeURIComponent(card.workstream.id!)}?evidence=1`):await getJson(`/api/state?q=${encodeURIComponent(result!.query)}&evidence=1`);if(detail)setDetail(body);else setResult(body);setEvidence(true)}catch{setError("Evidence is unavailable.")}finally{setEvidenceLoading(false)}}
function open(path:string){history.pushState({},"",path);loadRoute()}const card=detail?.card??result?.best;
return <><header><a className="brand" href="/" onClick={e=>{e.preventDefault();open("/")}}>W<span>Worktrail</span></a><span className="local">local · read-only</span><nav><a href="/">Search</a><a href="#status">Index status</a></nav></header><main><section id="search" className="content"><form onSubmit={search}><span className="glass">⌕</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask where work happened…" aria-label="Ask where work happened"/><button disabled={loading}>{loading?"Searching…":"Search"}</button></form>{loading&&<div className="notice">Loading work…</div>}{!loading&&!card&&!error&&!result&&!detail&&<><div className="intro"><h1>Find the thread. Recover the state.</h1><p>Search your local Codex work by what you remember.</p><div className="examples">{examples.map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div></div><Recent items={recent} open={open}/></>}{error&&<div className="empty error"><h2>Worktrail couldn’t load this view</h2><p>{error} Check that the local server and index are available.</p></div>}{result&&!card&&!loading&&<div className="empty"><h2>No matching work found</h2><p>Try a thread title, file path, working directory, or phrase from the work.</p></div>}{card&&<CardView card={card} detail={detail} evidence={evidence} evidenceLoading={evidenceLoading} toggleEvidence={toggleEvidence} open={open}/>}</section><aside id="status"><div className="statusHead"><h2>Index status</h2><button onClick={refreshStatus}>Refresh</button></div>{status?<><label>Database path</label><code>{status.databasePath}</code><label>Latest indexing run</label><p>{date(status.latestRun?.completedAt)} {status.latestRun&&<span className="success">{status.latestRun.status}</span>}</p>{Object.values(status.counts).every(x=>x===0)&&<p className="notice">No indexed sources yet. Run the index command to begin.</p>}<dl>{Object.entries(status.counts).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v.toLocaleString()}</dd></div>)}</dl><small>Last refreshed {date(refreshed)} · refreshes every 30s</small></>:<p>Loading metadata…</p>}{statusError&&<p className="statusWarning">{statusError}</p>}</aside></main><footer>All data stays on this machine. Evidence stays hidden until requested.</footer></>}
function Recent({items,open}:{items:Recent[];open:(x:string)=>void}){if(!items.length)return null;return <section className="recent"><h2>Recent workstreams</h2>{items.map(x=><button key={x.workstream.id} onClick={()=>open(`/workstreams/${encodeURIComponent(x.workstream.id)}`)}><b>{x.workstream.name}</b><span>{date(x.latestActivity)} · {x.confidence} confidence · {x.threadCount} thread{x.threadCount===1?"":"s"}</span></button>)}</section>}
function Copy({text,label}:{text:string;label:string}){const [done,setDone]=useState(false);return <button className="copy" onClick={()=>navigator.clipboard.writeText(text).then(()=>{setDone(true);setTimeout(()=>setDone(false),1200)})}>{done?"Copied":label}</button>}
function CardView({card,detail,evidence,evidenceLoading,toggleEvidence,open}:{card:Card;detail:{workstream:{status:string;aliases:string[]}}|null;evidence:boolean;evidenceLoading:boolean;toggleEvidence:()=>void;open:(x:string)=>void}){return <article className="card"><div className="cardHead"><div><h1>{card.workstream.name}</h1><span className="origin">{card.workstream.origin}{detail?` · ${detail.workstream.status}`:""}</span>{card.workstream.id&&!detail&&<button className="detailLink" onClick={()=>open(`/workstreams/${encodeURIComponent(card.workstream.id!)}`)}>Open workstream →</button>}</div><div className="score"><span className={`dot ${card.confidence}`}/><b>{card.confidence}</b><i/>Score <strong>{card.score.toFixed(2)}</strong></div></div>{detail&&detail.workstream.aliases.length>0&&<Section title="Aliases"><div className="files">{detail.workstream.aliases.map(x=><code key={x}>{x}</code>)}</div></Section>}<div className="facts"><Fact label="Latest activity" value={date(card.latestActivity)}/><Fact label="Best thread" value={card.bestThread.title??"Untitled thread"}/><Fact label="Related threads" value={String(card.relatedThreads.length)}/><div className="wide"><label>Resume UUID</label><div className="copyRow"><code>{card.bestThread.resumeRef}</code><Copy text={card.bestThread.resumeRef} label="Copy UUID"/><Copy text={`codex resume ${card.bestThread.resumeRef}`} label="Copy command"/></div></div><Fact label="Working directory" value={card.cwd??"—"} mono/></div><Section title="Related files"><div className="files">{card.relatedFiles.length?card.relatedFiles.map(x=><code key={x}>{x}</code>):<span className="muted">No related files recorded.</span>}</div></Section><Section title="Why this matched"><div className="signals">{card.signals.map(s=><span key={s.type} title={s.detail}>✓ {labels[s.type]??s.type}</span>)}</div></Section><Section title="Related threads"><div className="threads">{card.relatedThreads.map(t=><div className="thread" key={t.externalId}><div><b>{t.title??"Untitled thread"}</b>{t.archived&&<small>Archived</small>}</div><time>{date(t.lastActivity)}</time><code>{t.resumeRef}</code></div>)}</div></Section><button className="disclose" disabled={evidenceLoading} onClick={toggleEvidence} aria-expanded={evidence}>{evidenceLoading?"Loading evidence…":evidence?"⌃ Hide evidence":"⌄ Show evidence"}</button><p className="hint">Bounded, redacted excerpts fetched only when disclosed.</p>{evidence&&<div className="evidence">{card.latestEvidence.length?card.latestEvidence.map((x,i)=><div key={i}><div><b>{x.kind}</b><span>{date(x.occurredAt)} · source line {x.recordLine}</span></div><p>{x.excerpt}</p></div>):<p className="notice">No evidence excerpts are available.</p>}</div>}</article>}
function Fact({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className={mono?"wide":""}><label>{label}</label>{mono?<code>{value}</code>:<p>{value}</p>}</div>}; function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="section"><h3>{title}</h3>{children}</section>}
createRoot(document.getElementById("root")!).render(<App/>);
